#!/bin/bash

#-----------
# Configurations
#-----------

DEPLOYKEYS_USER=${DEPLOYKEYS_NAME-root}
DEPLOYKEYS_HOSTNAME=${DEPLOYKEYS_URL-github}
DEPLOYKEYS_HOSTURL=${DEPLOYKEYS_URL-github.com}

#-----------
# Configurations
#-----------

USER_HOME="$(getent passwd $DEPLOYKEYS_USER | awk -F ':' '{print $6}')"

echo "  -- Adding $DEPLOYKEYS_HOSTNAME to ${USER_HOME}/.ssh/known_hosts"
ssh-keyscan -H $DEPLOYKEYS_HOSTURL 2> /dev/null > ${USER_HOME}/.ssh/known_hosts
