#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

USER=${USER-deployer}
GROUP=${GROUP-www-data}
SSHKEYS=${SSHKEYS=false}

#-----------
# Install Script
#-----------

if [[ ! -e /home/$USER ]]; then
  notify "  -- Creating $USER user"
  if [[ "$OS" == "ubuntu" ]]; then
    if [[ "$PASSWD" == "disabled" ]]; then
      adduser --disabled-password --gecos "" $USER
    elif [[ "$PASSWD" == "" ]]; then
      adduser $USER
    else
      adduser $USER
      ./submodules/deploykeys/passwd $USER $PASSWD
    fi
  else
    useradd $USER
    if [[ "$PASSWD" != "disabled" ]] && [[ "$PASSWD" != "" ]]; then
      ./submodules/deploykeys/passwd $USER $PASSWD
    fi
  fi
else
  debug "  -- $USER user already exists"
fi

if [[ "$SSHKEYS" == true ]]; then
  if [[ ! -e /home/$USER/.ssh/id_dsa ]]; then
    OWNER="$USER:$GROUP" ./submodules/bootstrap/mkdir /home/$USER/.ssh
    su $USER -c ./submodules/deploykeys/sshkeys /home/$USER/.ssh/id_dsa
  fi
elif [[ "$SSHKEYS" != false ]]; then
  if [[ ! -e /home/$SSHKEYS/.ssh ]]; then
    warn "  -- WARNING, unable to copy keys from $SSHKEYS to $USER"
  elif [[ ! -e /home/$USER/.ssh ]]; then
    notify "  -- Copying SSH access from $SSHKEYS to $USER"
    cp -R /home/$SSHKEYS/.ssh /home/$USER/.ssh
    chown -R $USER:$GROUP /home/$USER/.ssh
  else
    debug "  -- Keys already setup for $USER"
  fi
fi


