#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
# set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

DEPLOYKEYS_USER=${DEPLOYKEYS_USER-root}
DEPLOYKEYS_KEYNAME=${DEPLOYKEYS_KEYNAME-id_dsa}
DEPLOYKEYS_KNOWN_HOSTS=${DEPLOYKEYS_KNOWN_HOSTS-known_hosts}
DEPLOYKEYS_ADD_GITHUB=${DEPLOYKEYS_ADD_GITHUB-false}
DEPLOYKEYS_ADD_BITBUCKET=${DEPLOYKEYS_ADD_BITBUCKET-false}

#-----------
# Install Script
#-----------

notify "Installing deploykeys..."

if [[ "$LOGLEVEL" -le "$DEBUG_LEVEL" ]]; then
  DEPLOYKEYS_OUTPUT=/tmp/deploykeys_install.log
else
  DEPLOYKEYS_OUTPUT=/dev/null
fi

if [[ "`which expect 2> /dev/null`" == "" ]]; then
  notify "  -- Installing expect"
  if [[ "$OS" == "redhat" ]] || [[ "$OS" == "centos" ]]; then
    debug "  -- yum install expect -y"
    yum install expect -y > $DEPLOYKEYS_OUTPUT 2>&1
    debug_all $DEPLOYKEYS_OUTPUT
  else
    debug "  -- apt-get install expect -y"
    DEBIAN_FRONTEND=noninteractive apt-get install expect -y > $DEPLOYKEYS_OUTPUT 2>&1
    debug_all $DEPLOYKEYS_OUTPUT
  fi
else
  debug "  -- expect already installed"
fi

if [[ "`which wget 2> /dev/null`" == "" ]]; then
  debug "  -- Using getent to find home directory of $DEPLOYKEYS_USER"
  USER_HOME="$(getent passwd $DEPLOYKEYS_USER | awk -F ':' '{print $6}')"
elif [[ "$DEPLOYKEYS_USER" == root  ]]; then
  debug "  -- Assuming /root home directory for $DEPLOYKEYS_USER"
  USER_HOME=/root
elif [[ "$DEPLOYKEYS_USER" == "$USER" ]]; then
  debug "  -- Using \$HOME as the home directory current user $USER"
  USER_HOME=$HOME
else
  error "Unable to determine the home directory of $DEPLOYKEYS_USER"
  exit 1
fi

debug "  -- Home directory: $USER_HOME"

mkdir -p ${USER_HOME}/.ssh

if [[ -e ./assets/${DEPLOYKEYS_KEYNAME} ]]; then
  notify "  -- Setting public key ${USER_HOME}/.ssh/${DEPLOYKEYS_KEYNAME}"
  cp ./assets/${DEPLOYKEYS_KEYNAME} ${USER_HOME}/.ssh/
  cp ./assets/${DEPLOYKEYS_KEYNAME}.pub ${USER_HOME}/.ssh/
else
  debug "  -- No public key provided in ./assets/${DEPLOYKEYS_KEYNAME}"
fi

if [[ -e ./assets/${DEPLOYKEYS_KNOWN_HOSTS} ]]; then
  notify "  -- Setting ${USER_HOME}/.ssh/known_hosts"
  cp ./assets/${DEPLOYKEYS_KNOWN_HOSTS} ${USER_HOME}/.ssh/known_hosts
else
  debug "  -- No known hosts provided in ./assets/${DEPLOYKEYS_KNOWN_HOSTS}"
fi

if [[ "$DEPLOYKEYS_ADD_GITHUB" == true ]]; then
  DEPLOYKEYS_USER=$DEPLOYKEYS_USER DEPLOYKEYS_HOSTNAME=github DEPLOYKEYS_URL=github.com ./submodules/deploykeys/add
else
  debug "  -- Skipping github keys"
fi

if [[ "$DEPLOYKEYS_ADD_BITBUCKET" == true ]]; then
  DEPLOYKEYS_USER=$DEPLOYKEYS_USER DEPLOYKEYS_HOSTNAME=bitbucket DEPLOYKEYS_URL=bitbucket.org ./submodules/deploykeys/add
else
  debug "  -- Skipping bitbucket keys"
fi

notify "DONE, Installing deploykeys."