#!/bin/bash

#-----------
# Configurations
#-----------

DEPLOYKEYS_USER=${DEPLOYKEYS_NAME-root}
DEPLOYKEYS_KEYNAME=${DEPLOYKEYS_KEYNAME-id_dsa}
DEPLOYKEYS_KNOWN_HOSTS=${DEPLOYKEYS_NAME-known_hosts}

DEPLOYKEYS_ADD_GITHUB=${DEPLOYKEYS_ADD_GITHUB-true}


#-----------
# Install Script
#-----------

echo "Installing deploykeys..."

USER_HOME="$(getent passwd $DEPLOYKEYS_USER | awk -F ':' '{print $6}')"

mkdir -p ${USER_HOME}/.ssh

if [[ -e ./assets/${DEPLOYKEYS_KEYNAME} ]]; then
  echo "  -- Setting public key ${USER_HOME}/.ssh/${DEPLOYKEYS_KEYNAME}"
  cp ./assets/${DEPLOYKEYS_KEYNAME} ${USER_HOME}/.ssh/
  cp ./assets/${DEPLOYKEYS_KEYNAME}.pub ${USER_HOME}/.ssh/
fi

if [[ -e ./assets/${DEPLOYKEYS_KNOWN_HOSTS} ]]; then
  echo "  -- Setting ${USER_HOME}/.ssh/known_hosts"
  cp ./assets/${DEPLOYKEYS_KNOWN_HOSTS} ${USER_HOME}/.ssh/known_hosts
fi

if [[ "$DEPLOYKEYS_ADD_GITHUB" == true ]]; then
  echo "  -- Adding github to ${USER_HOME}/.ssh/known_hosts"
  ssh-keyscan -H github.com > ${USER_HOME}/.ssh/known_hosts
fi

echo "DONE, Installing deploykeys."